# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Approximate Bayesian Inference Team
logo: assets/images/riken-transparent.png
email:
description: >- # this means to ignore newlines until "baseurl:"
  ABI at RIKEN AIP
twitter_username:
github_username:
#minimal_mistakes_skin: "dark"
search: false
author_profile: true
future: true #show future posts
url: "https://team-approx-bayes.github.io"
repository: "team-approx-bayes/team-approx-bayes.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 100 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Approximate Bayesian Inferen Team"
  #avatar : "/assets/images/Riken_Logo.png"
  bio    : "
  This is the webpage of the Approximate Bayesian Inference Team @ [AIP RIKEN](https://www.riken.jp/en/research/labs/aip/).
  <br><br>
  The team goal is to develop algorithms that allow machines to autonomously learn, perceive and interact with the environment.
  <br><br>
  Our works focus on a diverse set of machine learning areas: approximate inference, online learning, deep learning, continual learning, active learning.
  We develop novel bulding on top of a wide array of fields such as optimization, PAC-Bayesiaan statistics, information geometry and more.
  <br><br>
  If you are interested in joining us, please check the news and the people page.
  <br>
  "
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/emtiyazkhan"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/team-approx-bayes"




footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/team-approx-bayes"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/EmtiyazKhan"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

scholar:
   source: ./_bibliography
   sort_by: year,month
   bibliography_list_tag: "ul.no-bullet"

# Collections
collections:
  people:
    output: false
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: "_posts/"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _people
  - scope:
      path: ""
      type: people
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# placeholder profile image
teaser: /assets/images/placeholder_people_200.png
